services:
  - type: web
    name: yii2-backend
    env: php
    buildCommand: |
      composer install --no-dev --prefer-dist --optimize-autoloader
      php yii migrate --interactive=0
    startCommand: php -S 0.0.0.0:$PORT -t backend/web